### ISSUE TITLE
Create/Update course API

### ISSUE THREAD

**Issue by AdrienLemaire** [carpiediem/memrise-enhancement-suite#1]
Hello,

Ben Whately has copied the course [JLPT N2 Vocab](http://www.memrise.com/course/556/jlpt-n2-vocab-9/)  to [JLPT N2 Vocab (copy)](http://www.memrise.com/course/736114/jlpt-n2-vocab-copy/), for me to edit it and reorder all the words following [a frequency list](https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Japanese2015_10000).

I could crawl all items using your api documentation, but it's not possible to fetch the "Part of Speech" Column. Moreover, I do not want to create new items, but reuse those items instead.

Hence I'd like to bulk upload the list of item ids and level name, but it's not possible.

How did you investigate the current api and found all the calls described in your wiki ? If I can use the same technique to figure out what call I need in my case, that would be great.

Thank you!

**Comment by carpiediem** [comment]
I used the JavaScript console to watch server requests, then I poked around in the MEMRISE object that is loaded into the browser's memory during testing.  If you find anything interesting, let me know and we can add to the wiki.
