### ISSUE TITLE
Has course endpoint changed?

### ISSUE THREAD

**Issue by raineorshine** [carpiediem/memrise-enhancement-suite#2]
The pool endpoint still works, but I can't seem to get the course endpoint to work. Do you know if it has changed?

http://www.memrise.com/api/course/get?course_id=335725

**Comment by raineorshine** [comment]
I did find this url:
http://www.memrise.com/ajax/session/?course_id=335725&level_index=1&session_slug=preview

**Comment by carpiediem** [comment]
It appears that you're right.  It looks like the session url you listed is the next-best thing, since I can't seem to find a replacement URL for the course endpoint.  I'll update the wiki.

**Comment by raineorshine** [comment]
Thanks!
